### PR TITLE
Update multiple sources

### PR DESCRIPTION
**Pull request by cachgill**
This is a fix for https://github.com/Anifacted/lerna-update-wizard/issues/58.

This is probably not the most efficient way of modifying the packages, since it writes version updates separately for each dependency type, but I wanted to avoid a larger refactor.

### CODE REVIEW

**Comment by Anifacted** [comment]
Thanks! I'll take a look at this later today. Looks like a few tests need to be adjusted :)

**Comment by cachgill** [comment]
I apologize, the tests were taking a while to run on my local machine so I pushed the changes to let them run in the pipeline. I'm not sure what's throwing the error in the test. I did some manual testing and I'm able to both create a branch + commit and just a commit without creating a branch, all within our private repo.

**Comment by cachgill** [comment]
I've identified the reason for the failing test, I'll hopefully have a commit pushed in a little bit.

**Comment by cachgill** [comment]
Thanks!

**Pull request merged**
